baseURL = 'https://blog.shjoo.io'
languageCode = 'Ko-kr'
title = 'David Dev Blog'
theme = "PaperMod"
paginate = 5
min_version = "0.83.0"
description = "안녕하세요 "

[params]
defaultTheme = "lgiht"
name = "shjoo"
license = "MIT"
licenselink = "https://github.com/adityatelange/hugo-PaperMod/blob/master/LICENSE"
comments = true

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/gnshjoo"



[minify]
disableXML = true
minifyOutput = true


[author]
  name = "shjoo"
  homepage = "https://github.com/gnshjoo"

[markup.highlight]
  noClasses = false